MODULE PROGRAM_SETTINGS_TO_BE_SHARED,0
FILE 1,C:\users\dgilmore\Graduate.School\Adamowicz.Research\cgauss\shared settings.f90
VAR METHODOPT,1,0,,: 1,0,0,0,1,0,1
VAR TEST,1,0,,: 1,0,0,0,1,0,1
VAR IMODE,1,0,,: 1,0,0,0,1,0,1
VAR STGROWPER,1,0,,: 1,0,0,0,1,0,1
VAR ISTEND,1,0,,: 1,0,0,0,1,0,1
VAR PREOPT,1,0,,: 1,0,0,0,1,0,1
VAR STGROW,1,0,,: 1,0,0,0,1,0,1
VAR RESTART,1,0,,: 1,0,0,0,1,0,1
VAR METHODGEN,1,0,,: 1,0,0,0,1,0,1
END
